[System.Serializable]
public class TechEffect
{
    public EffectType effectType;
    public int value;
    public override string ToString() {
        return "";
    }
}


public enum EffectType
{
    ___NONE___ = 0,

    ___SHIP_EFFECTS___ = 1000,
    BOOST_THRUST,
    NORMAL_THRUST,
    ROTATION_SPEED,
    WARP_JUMP_DISTANCE,

    ___WEAPON_EFFECTS___ = 2000,
    ACCURACY,
    BURST_FIRE,
    DAMAGE,
    DROP_OFF,
    EXPLOSION_SIZE,
    FIRE_RATE,
    MUNITION_COUNT,
    MUNITION_SIZE,
    MUNITION_SPEED,
    PIERCING,
    PIERCE_PROBABILITY,
    _ALL_WEAPONS_,

    ___ORBIT___ = 3000,
    ALIEN_SPAWN_DISTANCE,
    MAP_SIZE,
    MINIMAP_ZOOM,
    SATELLITE_COUNT,
    SATELLITE_RANGE,
    SATELLITE_XP,
    _ALL_SATELLITES_ = 3500,

    ___CIVIC___ = 4000,
    POPULATION_GROWTH_TICK_VALUE,
    POPULATION_GROWTH_TICK_RATE,
    POPULATION_GROWTH_RANDOM_PROB,
    POPULATION_GROWTH_RANDOM_VALUE,
    XP_PASSIVE_GAIN,
    XP_KILL_GAIN,
    POPULATION_XP_GAIN_MODIFIER,
    DAMAGE_REDUCTION,
    RETALIATION_COOLDOWN,
    RETALIATION_COUNT,
    RETALIATION_NUKES,
    EMERGENCY_REPOPULATION,

    ___UNLOCKS___ = 8000,
    UNLOCK_BOOST,
    UNLOCK_TUNNEL_WARP,
    UNLOCK_WEAPON_2,
    UNLOCK_WEAPON_3,
    UNLOCK_WEAPON_4,
    UNLOCK_ICONS,
    UNLOCK_SATELLITE_1,
    UNLOCK_SATELLITE_2,
    UNLOCK_SATELLITE_3,
    UNLOCK_SPACE_STATION,
    UNLOCK_RETALIATION,
    UNLOCK_EARTH_MISSILES,

    ___VICTORY___= 9000,
    START_MISSION,
    START_COLLECTION_MISSION,
    START_SCANNING_MISSION,
    START_PROBE_MISSION,
    PROTOTYPE_WEAPON,
    START_FINALE_MISSION,

    FINISH_COLLECTION_MISSION = 9100,
    FINISH_SCANNING_MISSION,
    FINISH_PROBE_MISSION,
    FINISH_FINALE_MISSION,

    ADD_SCORE = 9900,
    WIN_GAME = 9999
}